''' Retrosheet game log data formats '''

gl_format = [
    'date',
    'gnum',
    'weekday',
    'teamid_vis',
    'league_vis',
    'gnum_vis',
    'teamid_home',
    'league_home',
    'gnum_home',
    'score_vis',
    'score_home',
    'outs',
    'day_night',
    'completion',
    'forfeit',
    'protest',
    'parkid',
    'attendance',
    'length',
    'line_vis',
    'line_home',
    'off_ab_vis',
    'off_hits_vis',
    'off_doubles_vis',
    'off_triples_vis',
    'off_hr_vis',
    'off_rbi_vis',
    'off_sh_vis',
    'off_sf_vis',
    'off_hbp_vis',
    'off_bb_vis',
    'off_ibb_vis',
    'off_k_vis',
    'off_sb_vis',
    'off_cs_vis',
    'off_gdp_vis',
    'off_ci_vis',
    'off_lob_vis',
    'pitch_pcount_vis',
    'pitch_indiver_vis',
    'pitch_teamer_vis',
    'pitch_wildpitch_vis',
    'pitch_balk_vis',
    'def_putouts_vis',
    'def_assist_vis',
    'def_err_vis',
    'def_pb_vis',
    'def_dplays_vis',
    'def_tplays_vis',
    'off_ab_home',
    'off_hits_home',
    'off_doubles_home',
    'off_triples_home',
    'off_hr_home',
    'off_rbi_home',
    'off_sh_home',
    'off_sf_home',
    'off_hbp_home',
    'off_bb_home',
    'off_ibb_home',
    'off_k_home',
    'off_sb_home',
    'off_cs_home',
    'off_gdp_home',
    'off_ci_home',
    'off_lob_home',
    'pitch_pcount_home',
    'pitch_indiver_home',
    'pitch_teamer_home',
    'pitch_wildpitch_home',
    'pitch_balk_home',
    'def_putouts_home',
    'def_assist_home',
    'def_err_home',
    'def_pb_home',
    'def_dplays_home',
    'def_tplays_home',
    'ump_1b_id',
    'ump_1b_name',
    'ump_2b_id',
    'ump_2b_name',
    'ump_3b_id',
    'ump_3b_name',
    'ump_lf_id',
    'ump_rf_name',
    'field86',
    'field87',
    'field88',
    'field89',
    'field90',
    'field91',
    'field92',
    'field93',
    'field94',
    'field95',
    'field96',
    'field97',
    'field98',
    'field99',
    'field100',
    'field101',
    'field102',
    'field103',
    'field104',
    'field105',
    'field106',
    'field107',
    'field108',
    'field109',
    'field110',
    'field111',
    'field112',
    'field113',
    'field114',
    'field115',
    'field116',
    'field117',
    'field118',
    'field119',
    'field120',
    'field121',
    'field122',
    'field123',
    'field124',
    'field125',
    'field126',
    'field127',
    'field128',
    'field129',
    'field130',
    'field131',
    'field132',
    'field133',
    'field134',
    'field135',
    'field136',
    'field137',
    'field138',
    'field139',
    'field140',
    'field141',
    'field142',
    'field143',
    'field144',
    'field145',
    'field146',
    'field147',
    'field148',
    'field149',
    'field150',
    'field151',
    'field152',
    'field153',
    'field154',
    'field155',
    'field156',
    'field157',
    'field158',
    'field159',
    'field160',
    'field161'
]

gl_informats = {
    'date': 'str',
    'gnum': 'str',
    'weekday': 'str',
    'teamid_vis': 'str',
    'league_vis': 'str',
    'gnum_vis': 'str',
    'teamid_home': 'str',
    'league_home': 'str',
    'gnum_home': 'str',
    'score_vis': 'int',
    'score_home': 'int',
    'outs': 'int',
    'day_night': 'str',
    'completion': 'str',
    'forfeit': 'str',
    'protest': 'str',
    'parkid': 'str',
    'attendance': 'float',
    'length': 'int',
    'line_vis': 'str',
    'line_home': 'str',
    'off_ab_vis': 'int',
    'off_hits_vis': 'int',
    'off_doubles_vis': 'int',
    'off_triples_vis': 'int',
    'off_hr_vis': 'int',
    'off_rbi_vis': 'int',
    'off_sh_vis': 'int',
    'off_sf_vis': 'int',
    'off_hbp_vis': 'int',
    'off_bb_vis': 'int',
    'off_ibb_vis': 'int',
    'off_k_vis': 'int',
    'off_sb_vis': 'int',
    'off_cs_vis': 'int',
    'off_gdp_vis': 'int',
    'off_ci_vis': 'int',
    'off_lob_vis': 'int',
    'pitch_pcount_vis': 'int',
    'pitch_indiver_vis': 'int',
    'pitch_teamer_vis': 'int',
    'pitch_wildpitch_vis': 'int',
    'pitch_balk_vis': 'int',
    'def_putouts_vis': 'int',
    'def_assist_vis': 'int',
    'def_err_vis': 'int',
    'def_pb_vis': 'int',
    'def_dplays_vis': 'int',
    'def_tplays_vis': 'int',
    'off_ab_home': 'int',
    'off_hits_home': 'int',
    'off_doubles_home': 'int',
    'off_triples_home': 'int',
    'off_hr_home': 'int',
    'off_rbi_home': 'int',
    'off_sh_home': 'int',
    'off_sf_home': 'int',
    'off_hbp_home': 'int',
    'off_bb_home': 'int',
    'off_ibb_home': 'int',
    'off_k_home': 'int',
    'off_sb_home': 'int',
    'off_cs_home': 'int',
    'off_gdp_home': 'int',
    'off_ci_home': 'int',
    'off_lob_home': 'int',
    'pitch_pcount_home': 'int',
    'pitch_indiver_home': 'int',
    'pitch_teamer_home': 'int',
    'pitch_wildpitch_home': 'int',
    'pitch_balk_home': 'int',
    'def_putouts_home': 'int',
    'def_assist_home': 'int',
    'def_err_home': 'int',
    'def_pb_home': 'int',
    'def_dplays_home': 'int',
    'def_tplays_home': 'int',
    'ump_1b_id': 'str',
    'ump_1b_name': 'str',
    'ump_2b_id': 'str',
    'ump_2b_name': 'str',
    'ump_3b_id': 'str',
    'ump_3b_name': 'str',
    'ump_lf_id': 'str',
    'ump_rf_name': 'str',
    'field86': 'str',
    'field87': 'str',
    'field88': 'str',
    'field89': 'str',
    'field90': 'str',
    'field91': 'str',
    'field92': 'str',
    'field93': 'str',
    'field94': 'str',
    'field95': 'str',
    'field96': 'str',
    'field97': 'str',
    'field98': 'str',
    'field99': 'str',
    'field100': 'str',
    'field101': 'str',
    'field102': 'str',
    'field103': 'str',
    'field104': 'str',
    'field105': 'str',
    'field106': 'str',
    'field107': 'str',
    'field108': 'str',
    'field109': 'str',
    'field110': 'str',
    'field111': 'str',
    'field112': 'str',
    'field113': 'str',
    'field114': 'str',
    'field115': 'str',
    'field116': 'str',
    'field117': 'str',
    'field118': 'str',
    'field119': 'str',
    'field120': 'str',
    'field121': 'str',
    'field122': 'str',
    'field123': 'str',
    'field124': 'str',
    'field125': 'str',
    'field126': 'str',
    'field127': 'str',
    'field128': 'str',
    'field129': 'str',
    'field130': 'str',
    'field131': 'str',
    'field132': 'str',
    'field133': 'str',
    'field134': 'str',
    'field135': 'str',
    'field136': 'str',
    'field137': 'str',
    'field138': 'str',
    'field139': 'str',
    'field140': 'str',
    'field141': 'str',
    'field142': 'str',
    'field143': 'str',
    'field144': 'str',
    'field145': 'str',
    'field146': 'str',
    'field147': 'str',
    'field148': 'str',
    'field149': 'str',
    'field150': 'str',
    'field151': 'str',
    'field152': 'str',
    'field153': 'str',
    'field154': 'str',
    'field155': 'str',
    'field156': 'str',
    'field157': 'str',
    'field158': 'str',
    'field159': 'str',
    'field160': 'str',
    'field161': 'str'
}

game_stats = [
    'off_ab',
    'off_hits',
    'off_doubles',
    'off_triples',
    'off_hr',
    'off_rbi',
    'off_sh',
    'off_sf',
    'off_hbp',
    'off_bb',
    'off_ibb',
    'off_k',
    'off_sb',
    'off_cs',
    'off_gdp',
    'off_ci',
    'off_lob',
    'pitch_pcount',
    'pitch_indiver',
    'pitch_teamer',
    'pitch_wildpitch',
    'pitch_balk',
    'def_putouts',
    'def_assist',
    'def_err',
    'def_pb',
    'def_dplays',
    'def_tplays'
]

games_format = ['season', 'date', 'gnum', 'teamid', 'opponent', 'gid', 'host', 'outs', 'winner', 'runs_scored', 'runs_allowed', 'line', 'line_opp']